image: golang:latest

variables:
  NAME: transmission-filter

before_script:
  - mkdir -p $GOPATH/src/$(dirname $NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$NAME
  - cd $GOPATH/src/$NAME
  - go get

compile:
  script:
    - go build
  artifacts:
    paths:
      - $NAME
