image: golang:latest

variables:
  REPO_NAME: gitlab.com/aurelien.chabot/transmission-filter

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get

stages:
  - build

compile:
  stage: build
  script:
    - go build -o transmission-filter
  artifacts:
    paths:
      - transmission-filter
